# Generated by Django 5.1.7 on 2026-01-21 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_order_quantity_alter_order_hotel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='produce',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='farmer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.farmer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
